### ISSUE TITLE
谢谢手打的资源，但是希望好好检查一下......

### ISSUE THREAD

**Issue by cmygit** [Yfling/shoppingCart#10]
1.json文件的图片路径加了static目录，但是实际项目目录没有static目录，
"productImage":"static/img/goods-1.jpg",
"imgSrc":"static/img/part-1.jpg"

2.       <style type="text/css">
        .quantity input {
            width: 40px;
            padding: 5px 10px;
            text-align: center;
        }
    </style>
cart.html自定义样式quantity 类拼写错了，这很明显，打开网页一看就发现了...商品数量旁边没有加减号。

**Comment by Yfling** [comment]
@cmygit  对于你说的quantity拼写问题，自己确实没有检查到，谢谢指正

**Comment by Yfling** [comment]
@cmygit 实际项目的目录有static目录
