### ISSUE TITLE
不能解压包

### ISSUE THREAD

**Issue by rainysweet** [Yfling/shoppingCart#2]
下载完成后不能解压对应的包。提示无此文件或目录~

**Comment by Yfling** [comment]
不会啊，我这里是可以正常下载的

**Comment by rainysweet** [comment]
真的 我下了5次 还是提示不能解压。。不知道为什么 能否帮个忙 传个unit 纯净版的给我 我按照教程来谢谢，万分感谢。 penghaomiao110@163.com

**Comment by Yfling** [comment]
@rainysweet  已经发你邮箱了，注意查收~

**Comment by liyizehhh** [comment]
请问有大神知道克隆的项目怎么运行吗跪求

**Comment by jianqiao0313** [comment]
@liyizehhh 双击html

**Comment by stolennumber** [comment]
我也无法解压
