### ISSUE TITLE
克隆的项目可以运行吗？

### ISSUE THREAD

**Issue by liyizehhh** [Yfling/shoppingCart#6]
我想下载项目之后自己学习修改，但是不知道怎么运行看效果呀

**Comment by liyizehhh** [comment]
求大神解答一下可以吗

**Comment by Yfling** [comment]
直接双击Html文件即可运行

**Comment by Jingyuan0000** [comment]
是哪一个HTML文件呀？我用yarn run dev也运行不了 报错是说dev  command not found
